# CREATING A DATABASE .
create database collage;
#USING A DATABSE TO CREATE TABLE OR OTHERS.
use collage;
#MAKING A TABLE NAME COLLAGE.
CREATE TABLE student (
	id INT PRIMARY KEY,
    name VARCHAR(50),
    age INT NOT NULL
);
# TO CHECK THE TABLE FORMED.
SELECT * FROM student;
# PUTTING THE VALUES INTO THE TABLE.
INSERT INTO student VALUES(1, "RITIK", 18);
INSERT INTO student VALUES(2, "ROHAN", 19);
SELECT * FROM student;
INSERT INTO student VALUES(3, "MOHAN", 18);
SELECT * FROM student;


CREATE DATABASE SCHOOL;
USE SCHOOL;
CREATE TABLE CHILDEREN (
	id INT PRIMARY KEY,
    name CHAR(50),
    result FLOAT NOT NULL
);

INSERT INTO CHILDEREN VALUES(1, "RITIK", 84.4);
SELECT * FROM CHILDEREN;